[build]
  base = "./"  # Change to the correct base directory if needed
  command = "npm cache clean --force && npm install --legacy-peer-deps && npm run build"
  publish = "dist"  # Adjust this to match your actual build output directory
  node_version = "15.14.0"  # Ensure this matches your project's Node.js version
