[build]
  # Directory to change to before starting build
  base = "./"

  # Build command
  command = "npm run build"

  # Publish directory (where your built output will be deployed from)
  publish = "dist"  # Replace "dist" with your actual build output directory

  # Node.js version to use
  node_version = "15.14.0"  # Replace with your desired Node.js version

# Optionally configure build environment variables
# [build.environment]
#   VARIABLE_NAME = "value"
